// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCERLfSezbteL3si-cnou5lkoC9WinJe_s',
    appId: '1:695765628074:web:9d1564e9e7eb2544240cd3',
    messagingSenderId: '695765628074',
    projectId: 'pravah-c4ccc',
    authDomain: 'pravah-c4ccc.firebaseapp.com',
    storageBucket: 'pravah-c4ccc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Ccf4NxMU74wmlMYeU9aC-CeRamNlOgQ',
    appId: '1:695765628074:android:021199f0e9bfd5d4240cd3',
    messagingSenderId: '695765628074',
    projectId: 'pravah-c4ccc',
    storageBucket: 'pravah-c4ccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvLoOWfgIfRjo-9bzBMYLn3hH3b--nMnQ',
    appId: '1:695765628074:ios:5395519c396c740c240cd3',
    messagingSenderId: '695765628074',
    projectId: 'pravah-c4ccc',
    storageBucket: 'pravah-c4ccc.firebasestorage.app',
    iosBundleId: 'com.example.pravah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvLoOWfgIfRjo-9bzBMYLn3hH3b--nMnQ',
    appId: '1:695765628074:ios:5395519c396c740c240cd3',
    messagingSenderId: '695765628074',
    projectId: 'pravah-c4ccc',
    storageBucket: 'pravah-c4ccc.firebasestorage.app',
    iosBundleId: 'com.example.pravah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCERLfSezbteL3si-cnou5lkoC9WinJe_s',
    appId: '1:695765628074:web:ea1e4961f2316901240cd3',
    messagingSenderId: '695765628074',
    projectId: 'pravah-c4ccc',
    authDomain: 'pravah-c4ccc.firebaseapp.com',
    storageBucket: 'pravah-c4ccc.firebasestorage.app',
  );
}
